project:
  type: website

website:
  title: "Curro Campuzano Jiménez"
  navbar:
    right:
      - icon: github
        href: https://github.com/currocam
      - icon: twitter
        href: https://twitter.com/currocam
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


