project:
  type: website

website:
  title: "Curro Campuzano Jiménez"
  navbar:
    right:
      - icon: github
        href: https://github.com/currocam
      - icon: twitter
        href: https://twitter.com/currocam
      - text: CV
        icon: file-earmark-pdf
        href: https://github.com/currocam/currocam.github.io/blob/main/src/resume.pdf
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
